// Generated by ./build-aux/bin/authors.h-gen, do not edit by hand.

#define PACKAGE_SHORT_AUTHORS \


#define PACKAGE_AUTHORS \
  "Remi Faucheux <fauche_r@epita.fr>\n"                                      \
  "Henri Baudesson <baudes_h@epita.fr>\n"                                    \
  "Paul Carre <paul.carre@epita.fr>\n"
